#ifndef NET_CFG_H
#define NET_CFG_H

#define DBG_MBLOCK DBG_LEVEL_INFO
#define DBG_LIST DBG_LEVEL_INFO
#define DBG_QUEUE DBG_LEVEL_INFO
#define DBG_MSG DBG_LEVEL_INFO
#define DBG_PKTBUF DBG_LEVEL_INFO

#define EXMSG_MSG_CNT 10
#define EXMSG_LOCKER NLOCKER_THREAD

#define PKTBUF_BLK_SIZE 128
#define PKTBUF_BLK_COUNT 64
#define PKTBUF_BUF_COUNT 32
#endif // NET_CFG_H